name: Gitea

services:
  db:
    image: postgres:${POSTGRES_VERSION}-alpine
    container_name: gitea-db
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - db
    restart: unless-stopped
    labels:
      - wud.tag.include=^\d+\.\d+-alpine$$
      - trafik.enable=false

  gitea:
    image: gitea/gitea:${GITEA_VERSION}
    container_name: gitea
    depends_on:
      - db
    volumes:
      - gitea-data:/data:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE
      - GITEA__database__HOST
      - GITEA__database__NAME
      - GITEA__database__USER
      - GITEA__database__PASSWD
    ports:
      - "127.0.0.1:222:22"
      - "127.0.0.1:3005:3000"
    networks:
      - backend
      - nginx-proxy-manager_frontend
      - db
    restart: unless-stopped
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - treafik.enable=true
      - traefik.http.routers.gitea-gitea.rule=Host(`gitea.dhjensen.tech`)

networks:
  backend:
    driver: bridge
    external: true
  nginx-proxy-manager_frontend:
    driver: bridge
    external: true
  db:
    driver: bridge
    external: false

volumes:
  gitea-data:
  postgres-data:
